name: Angel

on: [push]

jobs: virtual assistant
  build:   python

    runs-on: pycharm

    steps:
    - uses: actions/checks date/checks time.
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
      -name: 
      run: 
      
